### ISSUE TITLE
ERROR: Illegal parameter number in definition of \blx@defformat@d.

### ISSUE THREAD

**Issue by raxod502** [jackson13info/mla13#21]
I get the following error on compiling `Sample.tex` with TeX Live 2016:

```
ERROR: Illegal parameter number in definition of \blx@defformat@d.

--- TeX said ---
<to be read again> 
                   4
l.56     {\usebibmacro{name:first-last}{#1}{#4
                                              }{#5}{#7}}
```

[Probably relevant](http://tex.stackexchange.com/a/299084/54018) (but is this package abandoned?)

**Comment by raxod502** [comment]
The problem actually came from a dependency, `biblatex-mla`, rather than `mla13` itself. Solved as follows:

```
sudo tlmgr update --self
sudo tlmgr update biblatex-mla
```

**Comment by qtheperfect** [comment]
```
/usr/bin/tlmgr: unexpected return value from verify_checksum: -5
```
for all commands

**Comment by raxod502** [comment]
Looks like a problem upstream in tlmgr. It is a notably flaky piece of software. Unfortunately, I know nothing more than you. Perhaps others have reported the problem elsewhere online :/

**Comment by raxod502** [comment]
Oh, although I'll point out that these days I don't use tlmgr directly anymore, preferring instead to install TeX Live exclusively from the system package manager.
